name: My5stPL
version: '1.0-SNAPSHOT'
main: dev.fiepaw.my5stpl.My5stPL
api-version: 1.19
author: FiePaw
commands:
  tutorialForm:
    description: "Tutorial Jadi pinter ada di yt gua :v"
    usage: /tutorialForm
    aliases: [smart, pinter]
